### ISSUE TITLE
'MCU' object has no attribute 'register_response'

### ISSUE THREAD

**Issue by Thinkersbluff** [Thinkersbluff/DGUS-Reloaded_for_CR6-DWIN-SET_Component#86]
When I upgraded the Klipper to v0.13.0-572-g88a71c3ck, Klipper reported: "Internal error during connect: 'MCU' object has no attribute 'register_response'"

Investigation revealed that this error makes the Klipper component of DGUS-Reloaded  incompatible with Klipper3D after  v0.13.0-572-g88a71c3ck.

The fix is to rename that function and refactor line 441 of t5uid1.py, 
  from: self.mcu.register_response(self._handle_t5uid1_received, "t5uid1_received")
  to:  self.mcu.register_serial_response(self._handle_t5uid1_received,
                          "t5uid1_received command=%c data=%*s")

This fix will be made permanent at the next release of DGUS-Reloaded For CR6 (is currently in test, but slightly delayed by this new bug.)

Unfortunately, this means that the new release will now not be backward-compatible with earlier versions of Klipper.

**Comment by Thinkersbluff** [comment]
Here is a copy of the modified t5uid1.py currently in development and test for the next release of the Klipper component.
You may not be able to just drop it into your system, but you can try to copy/paste that new line from here (around line 447) into your own t5uid1.py module, to try to work around that particular bug.
[t5uid1.py](https://github.com/user-attachments/files/25779511/t5uid1.py)

**Comment by Thinkersbluff** [comment]
Fixed in Release 2.0.0
